name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore workloads
        run: dotnet workload restore .code/StarterApp/StarterApp/StarterApp.csproj

      - name: Restore dependencies
        run: dotnet restore ./StarterApp.sln

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build
        run: dotnet build ./StarterApp.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./StarterApp.sln --configuration Release --no-build --verbosity normal
