name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: JustEnoughMod/DoxygenDeployAction@1.0.1
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
